analytics: {}
color:
  brandColors:
    - '#B0B8A0'
    - '#208090'
    - '#908858'
    - '#F0B048'
    - '#C8B078'
  brandStrength: 1
  lightness: 1
  rhythmicContrast: 1
  saturation: 0.146381
cta: {}
layout_spectrum: 1
name: 'holy shit '
opengraph: {}
purpose: {}
typography_spectrum: 0.754111
