name: 'holy shit '
favicon: null
layout_spectrum: 0.25946
typography_spectrum: 0.754111
title: holy-shit-ahhhh
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B0B8A0'
    - '#208090'
    - '#908858'
    - '#F0B048'
    - '#C8B078'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
